### ISSUE TITLE
Header background color on page reload

### ISSUE THREAD

**Issue by aguscha333** [danielfeelfine/header-shrink#2]
Hello, I've seemed to have encountered an issue with your plugin. When I open the page for the first time it all works fine and if I am positioned at the top of the page and hit refresh it all looks well too. 
The problem comes when I am at another position of the page (when the nav is suposed to be shrinked already) and hit refresh then. When the page refreshes, my position on the page stays the same but the nav is not shrinked.

If I may, I suggest you fix this by simply adding a call to the function scrollPage() at the beginning of the function init()
I tested it and it works perfectly.

Hope it helps and thanks for the great plugin

**Comment by danielfeelfine** [comment]
Hi @aguscha333. Thanks for give the feedback, your suggestion looks great.

You can send a [pull request](https://github.com/danielfeelfine/header-shrink/compare) with this improve. And then I will accept his.

**Comment by agch-dev** [comment]
This was solved in #3 . Closing issue
